Updated giphy Socket
eyedea-io/syncano-socket-giphy pull request #1
Opened 2018-10-29 08:43 UTC by mattlsp

2018-10-29 09:02 UTC, mkucharz commented
Remove whole `.dist` and add it to `.gitignore`.

2018-10-29 09:03 UTC, mkucharz requested changes

2018-10-29 09:03 UTC, mkucharz commented on .dist/package.json
> +  "description": "Description",
Missing description.

2018-10-29 09:03 UTC, mkucharz commented on README.md
> +[![CircleCI branch](https://img.shields.io/circleci/project/github/eyedea-io/syncano-socket-document-generator/master.svg)](https://circleci.com/gh/eyedea-io/syncano-socket-document-generator/tree/ma
`document-generator`?

2018-10-29 09:03 UTC, mkucharz commented on coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove whole `coverage` folder and make sure that it is in `.gitignore' (add `.gitignore` if missing).

2018-10-29 09:03 UTC, mkucharz commented on socket.yml
> +          description: giphy tag
Why not complete definition?

2018-10-29 09:03 UTC, mkucharz commented on socket.yml
> -keywords:
Move those keywords to `package.json`

2018-10-29 09:03 UTC, mkucharz commented on test/__mocks__/axios.js
> +import axios from 'axios'
This mock is not used. Delete it.

2018-10-29 09:03 UTC, mkucharz commented on test/__mocks__/fb.js
> +import fb from 'fb'
This mock is not used. Delete it.

2018-10-29 09:03 UTC, mkucharz commented on test/unit/endpoint.test.js
> +/* global describe it */
Rename filename to match source file.

2018-10-29 09:03 UTC, mkucharz commented on test/unit/endpoint.test.js
> +describe('generate', function () {
Change from `generate` from `random`.

2018-10-29 11:26 UTC, mattlsp commented
Changes added.

2018-10-30 09:24 UTC, mkucharz approved these changes

2018-10-30 09:24 UTC, merged